
function drx_sl_money_task_status( tsk, task_id )

	if not ( db.actor ) then
		return
	end

	if ( db.actor:money( ) >= tonumber( alun_utils.load_var( db.actor, (task_id .. "_fetch"), 0 ) ) ) then
		tsk.stage = 1
	else
		tsk.stage = 0
	end

end


function drx_sl_assault_mutant_task_status( tsk, task_id )

	if not ( db.actor ) then
		return
	end

	if ( tsk.stage == 1 ) then -- already completed
		return
	end

	local smart_id = alun_utils.load_var(db.actor, (task_id .. "_id") )
	if not ( smart_id ) then
		return "fail"
	end

	local smrt = SIMBOARD.smarts[smart_id]
	if not ( smrt ) then
		return "fail"
	end

	local smart = smrt.smrt
	if not ( smart ) then
		return "fail"
	end

	local smart_online = (smart.position:distance_to_sqr(db.actor:position()) <= alife():switch_distance()^2)
		
	--in case sim_avail is set true during the player's tsk
	if not( smart.sim_avail == nil or xr_logic.pick_section_from_condlist( actor, smart, smart.sim_avail ) == "true" ) then
		return "fail"
	end

	local tg = time_global( )
	if ( tsk.__check_smart_time and tg < tsk.__check_smart_time ) then
		return
	end
	tsk.__check_smart_time = (tg + 3000)

	alun_utils.save_var( db.actor, (task_id .. "_target_id"), nil )

	if ( smart.sim_avail == nil or xr_logic.pick_section_from_condlist( actor, smart, smart.sim_avail ) == "true" ) then
		for id,squad in pairs( SIMBOARD.squads ) do
			if ( squad ) and simulation_objects.is_on_the_same_level( squad, smart ) then
				if not ( squad.first_update ) then
					return -- not all squads are loaded yet!
				end
				if (squad.current_target_id and squad.current_target_id == smart.id and squad.current_action == 1) then

					if (is_squad_monster[squad.player_id]) and not (string.find(squad:name(),"simulation_tushkano") or string.find(squad:name(),"simulation_rat")) then
						alun_utils.save_var( db.actor, (task_id .. "_target_id"), squad.id )
						squad.stay_time = game.get_game_time( ) -- reset gametime so they don't leave
						return
					end

				end
			end
		end
	end
	
	smart.faction = nil
	
	if not (smart_online) then 
		return "fail" 
	end

	if ( tsk.stage == 0 ) then
		tsk.stage = 1
	end

end

function drx_sl_assault_zombied_task_status( tsk, task_id )

	if not ( db.actor ) then
		return
	end

	if ( tsk.stage == 1 ) then -- already completed
		return
	end

	local smart_id = alun_utils.load_var(db.actor, (task_id .. "_id") )
	if not ( smart_id ) then
		return "fail"
	end

	local smrt = SIMBOARD.smarts[smart_id]
	if not ( smrt ) then
		return "fail"
	end

	local smart = smrt.smrt
	if not ( smart ) then
		return "fail"
	end

	--in case sim_avail is set true during the player's tsk
	if not( smart.sim_avail == nil or xr_logic.pick_section_from_condlist( actor, smart, smart.sim_avail ) == "true" ) then
		return "fail"
	end

	local tg = time_global( )
	if ( tsk.__check_smart_time and tg < tsk.__check_smart_time ) then
		return
	end
	tsk.__check_smart_time = (tg + 3000)

	alun_utils.save_var( db.actor, (task_id .. "_target_id"), nil )

	if ( smart.sim_avail == nil or xr_logic.pick_section_from_condlist( actor, smart, smart.sim_avail ) == "true" ) then
		for id,squad in pairs( SIMBOARD.squads ) do
			if ( squad ) and simulation_objects.is_on_the_same_level( squad, smart ) then
				if not ( squad.first_update ) then
					return -- not all squads are loaded yet!
				end
				if (squad.current_target_id and squad.current_target_id == smart.id and squad.current_action == 1) then

					if (squad.player_id == "zombied") and not is_squad_monster[squad.player_id] then
						alun_utils.save_var( db.actor, (task_id .. "_target_id"), squad.id )
						squad.stay_time = game.get_game_time( ) -- reset gametime so they don't leave
						return
					end

				end
			end
		end
	end

	smart.faction = nil
	
	if ( tsk.stage == 0 ) then
		tsk.stage = 1
	end

end

function drx_sl_assault_task_status( tsk, task_id )

	if not ( db.actor ) then
		return
	end
	
	
	if ( tsk.stage == 1 ) then -- already completed
		return
	end

	local smart_id = alun_utils.load_var(db.actor, (task_id .. "_id") )
	if not ( smart_id ) then
		return "fail"
	end

	local smrt = SIMBOARD.smarts[smart_id]
	if not ( smrt ) then
		return "fail"
	end

	local smart = smrt.smrt
	if not ( smart ) then
		return "fail"
	end
	
	--in case sim_avail is set true during the player's tsk
	if not( smart.sim_avail == nil or xr_logic.pick_section_from_condlist( actor, smart, smart.sim_avail ) == "true" ) then
		return "fail"
	end

	-- Get tsk giver faction:
	local task_giver_faction = alun_utils.parse_list( task_manager.task_ini, task_id, "status_functor_params" )
	if ( #task_giver_faction < 1 ) then
		printf( "DRX SL Error: drx_sl_assault_task_status not supplied with tsk giver faction in status functor !!!" )
		return "fail"
	end

	-- List of all factions:
	local factions_list = {
		"stalker",
		"dolg",
		"freedom",
		"csky",
		"ecolog",
		"killer",
		"army",
		"bandit",
		"monolith"
	}
	
	-- Build list of mutual enemy factions:
	local enemy_faction_list = {}
	for i = 1, #factions_list do
		if ( game_relations.is_factions_enemies( factions_list[i], task_giver_faction[1] ) ) then
			table.insert( enemy_faction_list, factions_list[i] )
		end
	end

	-- Ensure an enemy faction was found:
	if ( #enemy_faction_list < 1 ) then
		printf( "DRX SL Error: drx_sl_assault_task_status failed, no enemy factions found !!!" )
		return "fail"
	end

	local tg = time_global( )
	if ( tsk.__check_smart_time and tg < tsk.__check_smart_time ) then
		return
	end
	tsk.__check_smart_time = (tg + 3000)

	alun_utils.save_var( db.actor, (task_id .. "_target_id"), nil )

	if ( smart.sim_avail == nil or xr_logic.pick_section_from_condlist( actor, smart, smart.sim_avail ) == "true" ) then
		for id,squad in pairs( SIMBOARD.squads ) do
			if ( squad ) and simulation_objects.is_on_the_same_level( squad, smart ) then
				if not ( squad.first_update ) then
					return -- not all squads are loaded yet!
				end
				if (squad.current_target_id and squad.current_target_id == smart.id and squad.current_action == 1) then
					for i = 1, #enemy_faction_list do
						if ( squad.player_id == enemy_faction_list[i] ) then
							alun_utils.save_var( db.actor, (task_id .. "_target_id"), squad.id )
							alun_utils.save_var( db.actor, (smart.id .. "_assault_target"), true )
							squad.stay_time = game.get_game_time( ) -- reset gametime so they don't leave
							squad.force_online = true
							return
						end
					end
				end
			end
		end
	end

	smart_faction = nil

	if not (smart.online) then return "fail" end
	
	if ( tsk.stage == 0 ) then
	
		alun_utils.save_var( db.actor, (smart.id .. "_assault_target"), nil )
		
		local id = tsk.task_giver_id
		local se_obj = id and alife():object(id)
		local giver_smart = se_obj and se_obj.m_smart_terrain_id and se_obj.m_smart_terrain_id ~= 65535 and alife():object(se_obj.m_smart_terrain_id)
	
		--printf("!"..tostring(giver_smart:name()))
	
		if (giver_smart) then
			printf("-new squad")
			smart.faction = task_giver_faction[1]
			if task_giver_faction[1] == "killer" then
			    local new_squad = SIMBOARD:create_squad(giver_smart, "merc_sim_squad_advanced")
				if (new_squad) then
				    printf("-created")
				    new_squad.scripted_target = smart:name()
				end
			else
			    local new_squad = SIMBOARD:create_squad(giver_smart,task_giver_faction[1].."_sim_squad_advanced")
			    if (new_squad) then
				    printf("-created")
				    new_squad.scripted_target = smart:name()
			    end
		    end
		end
		
		tsk.stage = 1
	end

end

function drx_sl_quest_item_task_1_status( tsk, task_id )

	if not ( db.actor ) then
		return
	end

	if db.actor:object( "drx_sl_quest_item_1" ) then
		tsk.stage = 1
		alun_utils.save_var( db.actor, "drx_sl_quest_stash_1_id", nil )
	else
		tsk.stage = 0
	end

end

function drx_sl_quest_item_task_2_status( tsk, task_id )

	if not ( db.actor ) then
		return
	end

	if db.actor:object( "drx_sl_quest_item_2" ) then
		tsk.stage = 1
		alun_utils.save_var( db.actor, "drx_sl_quest_stash_2_id", nil )
	else
		tsk.stage = 0
	end

end

function drx_sl_quest_item_task_3_status( tsk, task_id )

	if not ( db.actor ) then
		return
	end

	if db.actor:object( "drx_sl_quest_item_3" ) then
		tsk.stage = 1
		alun_utils.save_var( db.actor, "drx_sl_quest_stash_3_id", nil )
	else
		tsk.stage = 0
	end

end

function drx_sl_retrieve_item_task_status( tsk, task_id )

	-- Get item id from status functor params:
	local task_item_params = alun_utils.parse_list( task_manager.task_ini, task_id, "status_functor_params" )
	if ( #task_item_params < 1 ) then
		printf( "DRX SL Error: drx_sl_retrieve_item_task_status not supplied with item id in status functor !!!" )
		return "fail"
	end

	-- Check if player has item:
	if not ( db.actor ) then
		return
	end
	if db.actor:object( task_item_params[1] ) then
		tsk.stage = 1
	else
		tsk.stage = 0
	end

end

function temporary_permission_task_status( tsk, task_id )

	if not ( db.actor ) then
		return
	end
	
	local start_time = utils.load_ctime(db.actor,(task_id .. "_date"))	
	local complete_time = tonumber(alun_utils.load_var( db.actor, (task_id .. "_time"),0))
	local diff = game.get_game_time():diffSec(start_time)/60/60
		
	if (tsk.stage == 0) and (diff > complete_time) then
		
		local caption = axr_task_manager.get_task_title_text(task_id)
		local text = axr_task_manager.get_task_complete_text(task_id)
		db.actor:give_game_news(caption, text, "ui_inGame2_Sdelka", 0, 3000)
		xr_sound.set_sound_play(db.actor:id(), "pda_task")
		tsk.stage = 1
	end
	
	if (tsk.stage == 1) and (diff > complete_time+1) then return "complete" end
end


function research_anomaly_task_status(tsk, task_id)
	
	if not ( db.actor ) then
		return
	end
	
	p = alun_utils.parse_list(task_manager.task_ini,task_id,"status_functor_params")
	local anomaly = db.anomaly_by_name[p[1]]
				
	local scanner = "jup_b32_scanner_device"
	if (tsk.stage == 0) then
		if (db.actor:object(scanner)) then
			tsk.stage = 1
		end
	elseif (tsk.stage == 1) and (anomaly) and (anomaly.object) then
		local distance = heli_alife.distance_2d_sqr(db.actor:position(),anomaly.object:position())
		if (heli_alife.distance_2d_sqr(db.actor:position(),anomaly.object:position()) <= 5^2) then
			tsk.stage = 2
		end
	elseif (tsk.stage == 2) and (anomaly) and (anomaly.object) then
		give_info("jup_b32_scanner_can_place")
		if (heli_alife.distance_2d_sqr(db.actor:position(),anomaly.object:position()) > 5^2) then
			tsk.stage = 1
			disable_info("jup_b32_scanner_can_place")
		elseif not (db.actor:object(scanner)) then
			tsk.stage = 3
			disable_info("jup_b32_scanner_can_place")
		end
	end
end



function check_smart_under_faction_control(tsk,task_id)
	if not (db.actor) then
		return
	end
	local smart_id = utils.load_var(db.actor,task_id.."_id")
	if not (smart_id) then
		return "fail"
	end

	local smrt = SIMBOARD.smarts[smart_id]
	if not (smrt) then
		return "fail"
	end

	local smart = smrt.smrt
	if not (smart) then
		return "fail"
	end

	--in case sim_avail is set true during the player's tsk
	if not(smart.sim_avail == nil or xr_logic.pick_section_from_condlist(actor, smart, smart.sim_avail) == "true") then
		return "fail"
	end

	local faction_list = alun_utils.parse_list(task_manager.task_ini,task_id,"status_functor_params")

	local tg = time_global()
	if (tsk.__check_smart_time and tg < tsk.__check_smart_time) then
		return
	end
	tsk.__check_smart_time = tg+3000

	utils.save_var(db.actor,task_id.."_target_id",nil)

	if (smart.sim_avail == nil or xr_logic.pick_section_from_condlist(actor, smart, smart.sim_avail) == "true") then
		for id,squad in pairs(SIMBOARD.squads) do
			if (squad) and simulation_objects.is_on_the_same_level(squad, smart) then
				if not (squad.first_update) then
					return -- not all squads are loaded yet!
				end
				if (squad.current_target_id and squad.current_target_id == smart.id and squad.current_action == 1) then
					for i=1,#faction_list do
						if (faction_list[i] == "monster" and is_squad_monster[squad.player_id]) or (squad.player_id == faction_list[i]) then
							utils.save_var(db.actor,task_id.."_target_id",squad.id)
							squad.stay_time = game.get_game_time() -- reset gametime so they don't leave
							squad.force_online = true
							--printf("task_id = %s squad_id = %s",task_id,squad.id)
							return
						end
					end
				end
			end
		end
	end

	--if not (smart.online) then
	--	return "fail"
	--end

	--[[
	local last_target_id = utils.load_var(db.actor,task_id.."_target_id")
	if (last_target_id and axr_task_manager.actor_tagged_squad_by_id[last_target_id] ~= true) then
		return "fail"
	end
	--]]

	local a_to_f = {	["actor_stalker"] = "stalker",
						["actor_bandit"] = "bandit",
						["actor_ecolog"] = "ecolog",
						["actor_dolg"] = "dolg",
						["actor_freedom"] = "freedom",
						["actor_monolith"] = "monolith",
						["actor_army"] = "army",
						["actor_killer"] = "killer",
						["actor_csky"] = "csky"
	}

	smart.faction = nil

	local id = tsk.task_giver_id
	local se_obj = id and alife():object(id)
	if (se_obj and se_obj:community()) then		
		smart.faction = se_obj:community()
	end

	return "complete"
end

-- to check a specific smart given as a param
function specific_check_smart_under_faction_control(tsk,task_id)

	if not (db.actor) then
		return
	end
		
	local p = alun_utils.parse_list(task_manager.task_ini,task_id,"status_functor_params")
	local smart = p[1] and SIMBOARD.smarts_by_names[p[1]]
	if not (smart) then
		return "fail"
	end
	
	local smrt = SIMBOARD.smarts[smart.id]
	if not (smrt) then
		return "fail"
	end
	
	--in case sim_avail is set true during the player's tsk
	if not(smart.sim_avail == nil or xr_logic.pick_section_from_condlist(actor, smart, smart.sim_avail) == "true") then
		return "fail"
	end

	local tg = time_global()
	if (tsk.__check_smart_time and tg < tsk.__check_smart_time) then
		return
	end
	tsk.__check_smart_time = tg+1500

	utils.save_var(db.actor,task_id.."_target_id",nil)

	if (smart.sim_avail == nil or xr_logic.pick_section_from_condlist(actor, smart, smart.sim_avail) == "true") then
		
		for id,squad in pairs(SIMBOARD.squads) do
			if (squad) and simulation_objects.is_on_the_same_level(squad, smart) then
						
				if not (squad.first_update) then
					return -- not all squads are loaded yet!
				end
				
				if (squad.current_target_id and squad.current_target_id == smart.id and squad.current_action == 1) then
									
					for i=2,#p do
						if (p[i] == "monster" and is_squad_monster[squad.player_id]) or (squad.player_id == p[i]) then
							utils.save_var(db.actor,task_id.."_target_id",squad.id)
							squad.stay_time = game.get_game_time() -- reset gametime so they don't leave
							squad.force_online = true
							--printf("task_id = %s squad_id = %s",task_id,squad.id)
							return
						end
					end
				end
			end
		end
	end

	--if not (smart.online) then
	--	return "fail"
	--end

	--[[
	local last_target_id = utils.load_var(db.actor,task_id.."_target_id")
	if (last_target_id and axr_task_manager.actor_tagged_squad_by_id[last_target_id] ~= true) then
		return "fail"
	end
	--]]

	local a_to_f = {	["actor_stalker"] = "stalker",
						["actor_bandit"] = "bandit",
						["actor_ecolog"] = "ecolog",
						["actor_dolg"] = "dolg",
						["actor_freedom"] = "freedom",
						["actor_monolith"] = "monolith",
						["actor_army"] = "army",
						["actor_killer"] = "killer",
						["actor_csky"] = "csky"
	}

	smart.faction = nil

	local id = tsk.task_giver_id
	local se_obj = id and alife():object(id)
	if (se_obj and se_obj:community()) then		
		smart.faction = se_obj:community()
	end

	return "complete"
end

function check_smart_under_faction_control_staged(tsk,task_id)
	if not (db.actor) then
		return
	end
	if (tsk.stage == 1) then -- already completed
		return
	end
	local status = check_smart_under_faction_control(tsk,task_id)
	if (status == "fail") then
		return "fail"
	elseif (status == "complete" and tsk.stage == 0) then
		tsk.stage = 1
	end
end

function check_specific_smart_under_faction_control_staged(tsk,task_id)
	if not (db.actor) then
		return
	end
	if (tsk.stage == 1) then -- already completed
		return
	end
	local status = specific_check_smart_under_faction_control(tsk,task_id)
	if (status == "fail") then
		return "fail"
	elseif (status == "complete" and tsk.stage == 0) then
		tsk.stage = 1
		--printf("set %s on complete stage",task_id)
	end
end

function hostage_task(tsk,task_id)
	if not (db.actor) then
		return
	end

	local id = tonumber(utils.load_var(db.actor,task_id .. "_id"))
	local smart = id and alife_object(id)
	if (smart) then
		smart.locked = true
	end

	if (tsk.stage == 0) then
		if (db.actor:has_info("hostage_companion_task_1_hostage_rescued")) then
			tsk.stage = 1
		end
	elseif (tsk.stage == 1) then
		if not (axr_task_manager.is_task_giver_valid(tsk)) then
			local hud = get_hud()
			if (hud) then
				hud:HideActorMenu()
			end
			return "complete" -- complete task even though giver is dead/missing/deleted
		end
	end
end

function bounty_task(tsk,task_id)
	if not (axr_task_manager.is_task_giver_valid(tsk)) then
		return "fail"
	end
	
	--printf("tsk.stage "..tsk.stage)

	if (tsk.stage == 0) then
		local id = axr_task_manager.bounties_by_id[task_id]
		if not (id) then
			return "fail"
		end
		local se_obj = id and alife_object(id)
		if not (se_obj) then
			return "fail"
		end
		if not (IsStalker(nil,se_obj:clsid())) then
			return "fail"
		end
		
		if not (se_obj:alive()) then
			if se_obj.online then
				--let axr_task_manager.npc_on_death_callback() handle it
				tsk.stage = 1
				--printf("online")
			else
				--printf("offline")
				return "fail"
			end
		else
			--printf("alive")
		end
	elseif (tsk.stage == 254) then
		return "fail"
	end
end

function hunter_task(tsk,task_id)
	if not (axr_task_manager.is_task_giver_valid(tsk)) then
		return "fail"
	end

	if (tsk.stage == 0) then
		local id = axr_task_manager.bounties_by_id[task_id]
		if not (id) then
			return "fail"
		end
		local se_obj = id and alife_object(id)
		if not (se_obj) then
			return "fail"
		end
		if not (IsMonster(nil,se_obj:clsid())) then
			return "fail"
		end
		if not (se_obj:alive()) then
			if se_obj.online then
				tsk.stage = 1
			else
				return "fail"
			end
		end
	elseif (tsk.stage == 254) then
		return "fail"
	end
end

function actor_has_fetch_item(tsk,task_id)
	if not (db.actor) then
		return
	end
	--if not (axr_task_manager.is_task_giver_valid(tsk)) then
	--	return "fail"
	--end
		
	local section = db.actor and utils.load_var(db.actor,task_id.."_fetch")
		
	local item = section and db.actor:object(section)
	if (item ~= nil) then
		local count = utils.load_var(db.actor,task_id.."_fetch_count")
		if (count and count > 1) then
		 	local cnt = 0
			local function section_count(npc, item)
				if (item:section() == section) then
					cnt = cnt + 1
				end
			end
			
			db.actor:iterate_inventory(section_count, nil)
			
			if (cnt >= count) then
				tsk.stage = 1
			else
				tsk.stage = 0
			end
			return
		end
		tsk.stage = 1
	else
		tsk.stage = 0
	end
end

function check_if_enough_time_passed(tsk,task_id)
	if not (db.actor) then
		return
	end
	local p = alun_utils.parse_list(task_manager.task_ini,task_id,"status_functor_params")
	if not (p[1]) then
		printf("task_status_function not set up properly! check_if_killed_enough needs an extra param for squad story id! task_id=%s",task_id)
		return
	end

	local gt = utils.load_ctime(db.actor,task_id)
	if (gt == nil or game.get_game_time():diffSec(gt) >= tonumber(p[1])) then
		tsk.stage = 2
		return
	end
end

function check_if_killed_enough(tsk,task_id)
	local p = alun_utils.parse_list(task_manager.task_ini,task_id,"status_functor_params")
	if not (p[1]) then
		printf("task_status_function not set up properly! check_if_killed_enough needs an extra param for squad story id! task_id=%s",task_id)
		return
	end

	local squad = get_story_squad(p[1])
	if not (squad) then
		return
	end

	local id = squad:commander_id()
	local npc = db.storage[id] and db.storage[id].object
	if not (npc) then
		return
	end

	local total_kill_count, npc
	for k in self:squad_members() do
		local npc = db.storage[k.id] and db.storage[k.id].object
		if (npc) then
			total_kill_count = total_kill_count + (utils.load_var(npc,"s_kill_count") or 0)
		end
	end

	if (total_kill_count >= tonumber(p[2] or 5)) then
		return "complete"
	end
end

function check_if_looted_enough(tsk,task_id)
	local p = alun_utils.parse_list(task_manager.task_ini,task_id,"status_functor_params")
	if not (p[1]) then
		printf("task_status_function not set up properly! check_if_looted_enough needs an extra param for squad story id! task_id=%s",task_id)
		return
	end

	local squad = get_story_squad(p[1])
	if not (squad) then
		return
	end

	local id = squad:commander_id()
	local npc = db.storage[id] and db.storage[id].object
	if not (npc) then
		return
	end

	local total_loot_count, npc
	for k in squad:squad_members() do
		local npc = db.storage[k.id] and db.storage[k.id].object
		if (npc) then
			total_loot_count = total_loot_count + (utils.load_var(npc,"s_loot_count") or 0)
		end
	end

	if (total_loot_count >= tonumber(p[2] or 5)) then
		return "complete"
	end
end

function kill_scripted_squad_task_status(tsk,task_id)
		
	if not (db.actor) then
		return
	end

	if (tsk.stage == 0) then
	
		local params = alun_utils.parse_list(task_manager.task_ini,task_id,"status_functor_params")
		local target = params[1]
	
		if (not xr_conditions.squad_exist(nil,nil,{target})) then
			tsk.stage = 1
		end	
	end
end

function task_type_ecolog_gathered_tissue_samples(tsk,task_id)
	if (db.actor and tsk.stage == 0) then
		local count = utils.load_var(db.actor,task_id.."_tissue_count",0)
		local need = utils.load_var(db.actor,task_id.."_tissue_need",0)

		if (count >= need) then
			tsk.stage = 1
		else
			tsk.stage = 0
		end
	end
	return
end


function esc_m_trader_task_status_1(tsk,task_id)
		
	if not (db.actor) then
		return
	end

	if (tsk.stage == 0) then
		if (not xr_conditions.squad_exist(nil,nil,{"bandit_esc_smart_terrain_7_11"})) then
			tsk.stage = 1
		end	
	end
end

function ds2_gonta_quest_task_status(tsk,task_id)
		
	if not (db.actor) then
		return
	end

	if (tsk.stage == 0) then
	
		local start_time = utils.load_ctime(db.actor,(task_id .. "_date"))
		local diff = game.get_game_time():diffSec(start_time)/60/60

		if not (level.get_time_hours() > 4 and level.get_time_hours() < 19) then
			give_info("gonta_quest_time")
		else
			disable_info("gonta_quest_time")
			if (diff > 18) or (db.actor:has_info("gonta_quest_moved")) then
				dialogs.ds2_set_gonta_remove()
				disable_info("gonta_quest_moved")
				give_info("gonta_quest_failed")
				return "fail"
			end
		end
		
		if (not xr_conditions.squad_exist(nil,nil,{"ds2_lager_st_bandit_squad"})) then
			give_info("gonta_quest_finished")
			
			
			if (db.actor:has_info("gonta_quest_moved")) then
				disable_info("gonta_quest_moved")
			else
				disable_info("gonta_quest_time")
			end
			tsk.stage = 1
		end	
	end
	
	if (db.actor:has_info("gonta_quest_closed")) then
		return "complete"
	end
end

--------------------------------------------------------------
function kill_strelok(tsk,task_id)
	local squad = get_story_squad("legendary_strelok")
	if (squad) then
		for k in squad:squad_members() do
			local se_obj = alife_object(k.id)
			if (se_obj and not se_obj:alive()) then
				return "complete"
			end
		end
	end
end

function has_alife_info(tsk,task_id)
	if tsk.stage ~= 0 then return end
	local p = alun_utils.parse_list( task_manager.task_ini, task_id, "status_functor_params" )
	if (db.actor:has_info(p[1])) then
		tsk.stage = 1
	end
end